transport:
  type: streamable_http
operations:
  source: local
  paths:
    - ./graphql/weather/operations
schema:
  source: local
  path: ./graphql/weather/api.graphql
introspection:
  execute:
    enabled: true
  introspect:
    enabled: true
  search:
    enabled: true
