[package]
name = "apollo-mcp-server"
version.workspace = true
edition = "2024"
license = "Elastic-2.0"

[dependencies]
anyhow = "1.0.98"
apollo-compiler.workspace = true
apollo-federation.workspace = true
apollo-mcp-registry = { path = "../apollo-mcp-registry" }
buildstructor = "0.6.0"
clap = { version = "4.5.36", features = ["derive"] }
futures.workspace = true
lz-str = "0.2.1"
regex = "1.11.1"
reqwest.workspace = true
rmcp = { version = "0.1", features = [
  "server",
  "transport-io",
  "transport-sse-server",
] }
serde.workspace = true
thiserror.workspace = true
tokio.workspace = true
tracing.workspace = true
tracing-subscriber = { version = "0.3.19", features = ["env-filter"] }
tokio-util = "0.7.15"
webbrowser = "1.0.4"

[dev-dependencies]
insta = { workspace = true }
rstest = "0.25.0"

[lints]
workspace = true
